### ISSUE TITLE
@all-contributors add @Nik0lyaZ for translation

### ISSUE THREAD

**Issue by Nik0lyaZ** [ScratchAddons/contributors#146]
@all-contributors add @Nik0lyaZ for translation

**Comment by CST1229** [comment]
Uhh.. Comment on the [pinned issue](https://github.com/ScratchAddons/contributors/issues/136) instead of making an issue with the name.

**Comment by Nik0lyaZ** [comment]
@all-contributors add @Nik0lyaZ for translation (transifex.com/user/profile/Nikolyas)
