### ISSUE TITLE
README.md leads to wrong issue

### ISSUE THREAD

**Issue by LegoManiac04** [ScratchAddons/contributors#152]
In the README.md the link in _"Have contributed in any way? Read how to put your name [here](https://github.com/ScratchAddons/contributors/issue/12)."_ leads to a 404, and not the [correct link](https://github.com/ScratchAddons/contributors/issues/136).
Not a big issue, but I thought I would point it out.

**Comment by RedGuy12** [comment]
Feel free to PR.
