### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by GreypathPro** [ScratchAddons/contributors#164]
# SPAM POLICY

## Supported Versions

We have got versions from 3.4 till 4.1, so please check which one to use. There is no 3.5 as is was broken, so we removed it.

| Version | Supported          |
| ------- | ------------------ |
| 4.1.x   | :white_check_mark: |
| 4.0.x   | :white_check_mark: |
| 3.9.x   | :x:                |
| 3.8.x   | :white_check_mark: |
| 3.7.x   | :white_check_mark: |
| 3.6.x   | :x:                |
| 3.4.x   | :x:                |

## Reporting a issue

For reporting a issue you can:
1) Commit a file on it.
2) Report the problem to @GreypathPro.
3) Make a pull-request.

**Comment by RedGuy12** [comment]
what
