### ISSUE TITLE
Have contributed? Get your name on the list here! (February 2022)

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/contributors#183]
So, you have contributed in the Scratch Addons development, whether it's code, docs, or even an idea? If so, you are eligible for your name to be added to the list, and also be featured on https://scratchaddons.com/contributors.

We are following the all-contributors specification, and this repository is the catch-all contributors list on all repositories on the Scratch Addons' repository.

To be added, **comment on this issue with a mention to @all-contributors like the example below**. You actually don't need to follow this template exactly.

```
@all-contributors add <GitHub username> for <contributions>
```

`<GitHub username>` is **your username on GitHub**, the one that you will use to write the comment, not Scratch! 

`<contributions>` is one or many, of the valid types on [the emoji key](https://allcontributors.org/docs/en/emoji-key). Here are some examples:

- Have you added any code on [the SA repo](https://github.com/ScratchAddons/ScratchAddons)? Use `code` as the type.
- Have you improved [the docs](https://scratchaddons.com/docs)? Use `doc` as the type.
- Have you added a new addon image (ScratchAddons/website-v2#4)? Use `example` as the type.
- Are you a translator? Use `translation` as the type. (read below for further instructions!)

For example:

```
@all-contributors add @Hans5958 for bug
@all-contributors add @Hans5958 for code, translation, and doc
@all-contributors can you add @Hans5958 for ideas?
```

[Read more here](https://allcontributors.org/docs/en/bot/usage).

**Doing so will create a pull request, which we need to review and merge to have your name on the website.** You can do this in [the comment section of the issue below](#new_comment_field), or make a new issue (but it is discouraged).

To speed up the process, you can give proof of your contribution (a link, a picture, anything), but please put it on the created PR as messages on this issue is not monitored.

**For translators**: For the proof of your contribution, please send a message to `RedGuy12` [here](https://www.transifex.com/user/messages/compose/).

# [⬇️ Go directly to the new comment field! ⬇️](#new_comment_field)

For organization members, 

1. If you wanted to add someone else, you can do this here, but I recommend you to do it on #6, so people know that their name will be added on the list. That is, if you mention the issue/PR on the other repositories.
2. Please use the **squash merge**, not the commit merge.

**Comment by BarelySmooth** [comment]
@all-contributors add @BarelySmooth for code

**Comment by Chiroyce1** [comment]
@all-contributors add @Chiroyce1 for docs

**Comment by Evrick14** [comment]
@all-contributors add @Evrick14 translation

**Comment by Norbiros** [comment]
@all-contributors add Norbiros for translation

**Comment by Chiroyce1** [comment]
@all-contributors add @Chiroyce1 for code ([#4264](https://github.com/ScratchAddons/ScratchAddons/pull/4264))

**Comment by diaowinner** [comment]
@all-contributors add @diaowinner for translation

**Comment by johnny263** [comment]
@all-contributors add @johnny263 for translation

**Comment by Evrick14** [comment]
@all-contributors can you add @Evrick14 for ideas?

**Comment by Evrick14** [comment]
@all-contributors can you add @Hans5958 for ideas?

**Comment by Evrick14** [comment]
@all-contributors can you add @Evrick14 for ideas?

**Comment by Dhuls-Scratch** [comment]
@all-contributors add Dhuls-Scratch for code

**Comment by RedGuy12** [comment]
@all-contributors add @Dhuls-Scratch for code?

**Comment by RIMOPA** [comment]
@all-contributors add @RIMOPA for Ideas

**Comment by R081N-08** [comment]
@all-contributors add @R081N-08 for translation

**Comment by Jazza-231** [comment]
@all-contributors add <Jazza-231> for <Ideas (HD upload, etc)>

**Comment by RedGuy12** [comment]
> @all-contributors add Jazza-231 for Ideas

It doesn't work if you edit it

It should trigger on this quote tho

**Comment by RedGuy12** [comment]
@all-contributors add @Jazza-231 for Ideas

**Comment by shock59** [comment]
@all-contributors add @shock59 for video

**Comment by shock59** [comment]
@all-contributors add @Aid0nModder for video

**Comment by gaker19sc** [comment]
@all-contributors add @gaker19sc for translation

**Comment by BAndris0909** [comment]
@all-contributors add @BAndris0909 for translation

**Comment by GitHub027** [comment]
Where can i have source code? (I'm making an addon)

**Comment by Norbiros** [comment]
> Where can i have source code? (I'm making an addon)

Scratch Addons' source code? Here: https://github.com/ScratchAddons/ScratchAddons

**Comment by DNin01** [comment]
@all-contributors add @DNin01 for ideas

**Comment by CowBloke** [comment]
@all-contributors add CowBloke for translation

**Comment by MaterArc** [comment]
https://github.com/all-contributors add @MaterArc for bug reports, security, maintenance, and documentation.

**Comment by MaterArc** [comment]
@all-contributors add @MaterArc for bug

**Comment by Norbiros** [comment]
@all-contributors add @Norbiros for bug, code, doc

**Comment by RIMOPA** [comment]
@all-contributors add @RIMOPA translations

**Comment by MaterArc** [comment]
@all-contributors add @MaterArc for [bug](urlhttps://github.com/all-contributors add @MaterArc for https://github.com/ScratchAddons/ScratchAddons/issues/4927

**Comment by MaterArc** [comment]
@all-contributors add @MaterArc for [bug](https://github.com/all-contributors add @MaterArc for https://github.com/ScratchAddons/ScratchAddons/issues/4927)

**Comment by MaterArc** [comment]
@all-contributors add @MaterArc for bug (https://github.com/ScratchAddons/ScratchAddons/issues/4927)

**Comment by BroJac5246** [comment]
@all-contributors add @BroJac5246 for code, bug, and ideas

**Comment by CubesterYT** [comment]
@all-contributors add @CubesterYT for bug [4560](https://github.com/ScratchAddons/ScratchAddons/issues/4560)

**Comment by RedGuy12** [comment]
@all-contributors add @Jazza-231 for mod
@all-contributors add @Late-Is-Cool for mod

**Comment by RedGuy12** [comment]
https://github.com/all-contributors add @Jazza-231 for mod

**Comment by RedGuy12** [comment]
@all-contributors add @Late-Is-Cool for mod

**Comment by RedGuy12** [comment]
fine

**Comment by penguinmoose** [comment]
@all-contributors add @penguinmoose for example, ideas

**Comment by Hans5958** [comment]
@allcontributors add @FunctionalMetatable for code

**Comment by Wjplatformer** [comment]
@allcontributors add @Wjplatformer for translation and docs

**Comment by RedGuy12** [comment]
@allcontributors add @BelkaBoi for translate

**Comment by RedGuy12** [comment]
@allcontributors add @BelkaBoi for translation

**Comment by GitHub027** [comment]
@allcontributors add @GitHub027 for ideas and code

**Comment by GitHub027** [comment]
is it possible to contribute as non-logined (or banned user)?

**Comment by GitHub027** [comment]
no answers?

**Comment by Hans5958** [comment]
> is it possible to contribute as non-logined (or banned user)?

You could contribute in anyway, but you have to have a GitHub account if you want your name to the contributors page? If any, could you be more specific?

**Comment by Mel0n7** [comment]
@allcontributors add @mel0n7 for code

**Comment by Hans5958** [comment]
@all-contributors add @PurpleZen for code

**Comment by Hans5958** [comment]
@all-contributors add @DNin01 for code

**Comment by GitHub027** [comment]
> > is it possible to contribute as non-logined (or banned user)?
> 
> You could contribute in anyway, but you have to have a GitHub account if you want your name to the contributors page? If any, could you be more specific?

as non-logined or banned user on scratch

**Comment by iqnite** [comment]
@all-contributors add @iqnite for example

**Comment by iqnite** [comment]
@all-contributors add @iqnite for code
