### ISSUE TITLE
@R081N-08 (me) not on contributors list anymore

### ISSUE THREAD

**Issue by R081N-08** [ScratchAddons/contributors#198]
Yesterday, I was successfully added to the contributors list for translating, however, my name is now no longer there. I could be wrong, but after looking at .all-contributorsrc, it seems as if I have been replaced with somebody else by the bot (line 1132-1140).  I'd appreciate it if this could this be fixed. Thanks in regards!

**Comment by RedGuy12** [comment]
Whoops that was my fault
Looks like I accidentally removed someone else too

@all-contributors add rimopa for ideas
@all-contributors add @R081N-08 for translation

**Comment by RedGuy12** [comment]
@all-contributors add rimopa for ideas

**Comment by RedGuy12** [comment]
@all-contributors add @R081N-08 for translation
