### ISSUE TITLE
There should be fancy font types in Editor.

### ISSUE THREAD

**Issue by The-Coder2012** [ScratchAddons/contributors#271]
There should be fancy font types in the editor. This will reduce the work of going to a website and downloading the font and then upload it to a scratch project.

**Comment by Hans5958** [comment]
Please open an issue on https://github.com/ScratchAddons/ScratchAddons/issues instead.

**Comment by The-Coder2012** [comment]
Why are always bugging me

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
