### ISSUE TITLE
de'promoting on studios. its too much work having to remove and re invite scratchers just to de promote them.

### ISSUE THREAD

**Issue by jack-oid** [ScratchAddons/contributors#283]
is it a good idea?

**Comment by OneShot-Niko** [comment]
Pretty sure the only way this addon could work would be kicking and then inviting again - Unless there's some server communication (which is probably out of scope for SA) which allows for an autoaccept of it, that could still cause problems.

**Comment by CST1229** [comment]
And also, this repo is not the place for suggestions (those go on [the main repository](/ScratchAddons/ScratchAddons), and an issue has already been created and rejected there: ScratchAddons/ScratchAddons#3139)
