### ISSUE TITLE
when stop sign clicked 

### ISSUE THREAD

**Issue by jack-oid** [ScratchAddons/contributors#285]
![stop](https://github.com/ScratchAddons/contributors/assets/154941233/17ad8862-343d-4e6d-85e9-f335231ae1e9)
why don't we have this yet? we could code multiple games in one.

**Comment by CST1229** [comment]
wouldn't be compatible with people not using SA, also please suggest on [ScratchAddons/ScratchAddons](/ScratchAddons/ScratchAddons/issues) instead
