### ISSUE TITLE
Add allcontributors bot

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/contributors#5]
Add allcontributors bot on https://github.com/apps/allcontributors/installations/new on this repository, so people add themselves, with an agreement from ours in form of merging the PR. @WorldLanguages

**Comment by WorldLanguages** [comment]
Done. https://github.com/organizations/ScratchAddons/settings/installations/12523023

**Comment by Hans5958** [comment]
Nah, that's an owner-only page.
