### ISSUE TITLE
If you see this, your name will be (or have been) added to the contributor list

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/contributors#6]
If you see this issue on your issue/PR, your name will be (or have been) added to the contributor list. This list is shown on https://github.com/ScratchAddons/contributors and https://scratchaddons.com/contributors. This is done because no contributions is a wasted effort and we don't want your contributions to be overlooked.

If you don't want your name on the list, please tell us by creating an issue or by other means. Sorry for the inconvenience.

----

For organization members, 

1. I recommend you to mention the issue/PR from the other repositories so this issue will appear on them.
2. Please use the **squash merge**, not the commit merge.

**Comment by Hans5958** [comment]
@all-contributors add @TheColaber for code

**Comment by Hans5958** [comment]
@all-contributors add @pufferfish101007 for ideas

https://github.com/ScratchAddons/ScratchAddons/issues/468#issue-718841575

**Comment by Hans5958** [comment]
@all-contributors add @MashimbaTheHuman for ideas

https://github.com/ScratchAddons/ScratchAddons/issues/550#issue-726949045

**Comment by Hans5958** [comment]
@all-contributors add @MasimbaTheHuman for ideas

https://github.com/ScratchAddons/ScratchAddons/issues/550#issue-726949045

**Comment by Hans5958** [comment]
@all-contributors add samuraininja360 for ideas

https://github.com/ScratchAddons/ScratchAddons/issues/492#issue-721771796

**Comment by Hans5958** [comment]
@all-contributors add pufferfish101007 for code

**Comment by Hans5958** [comment]
@all-contributors add samuraininja360 for bug report

https://github.com/ScratchAddons/ScratchAddons/issues/493#issue-721773307

**Comment by Hans5958** [comment]
@all-contributors add pufferfish101007 for bug

**Comment by Hans5958** [comment]
@all-contributors add Explosion-Scratch for bug

**Comment by Hans5958** [comment]
@all-contributors add @Explosion-Scratch for bug

**Comment by Hans5958** [comment]
@all-contributors add @lisa-wolfgang for ideas

ScratchAddons/ScratchAddons#587 - ScratchAddons/ScratchAddons#596

**Comment by Hans5958** [comment]
@all-contributors add @lisa-wolfgang for bug reports

ScratchAddons/ScratchAddons#583 - ScratchAddons/ScratchAddons#585

**Comment by GrahamSH-LLK** [comment]
@all-contributors remove @GrahamSH-LLK

**Comment by MasimbaTheHuman** [comment]
Wait... how can someone be bug reports and ideas at the same time? @samuraninja360 did it.

**Comment by GrahamSH-LLK** [comment]
You can be any combination!

**Comment by GrahamSH-LLK** [comment]
@all-contributors add @MasimbaTheHuman for bug reports

**Comment by Hans5958** [comment]
@all-contributors add @Cool-Scratcher for bug

**Comment by Hans5958** [comment]
@all-contributors add @Mast3rGenius for code

ScratchAddons/ScratchAddons/#752

**Comment by Hans5958** [comment]
@all-contributors add @Daniel4-Scratch for code

ScratchAddons/ScratchAddons/#832

**Comment by Hans5958** [comment]
@all-contributors add @qucchia for code

ScratchAddons/ScratchAddons#880

**Comment by Hans5958** [comment]
@all-contributors add @mxmou for example

**Comment by Hans5958** [comment]
@all-contributors add @TheColaber for example

**Comment by Hans5958** [comment]
@all-contributors add @Hans5958 for example

**Comment by Hans5958** [comment]
@allcontributors add RustingRobot for translation

**Comment by GrahamSH-LLK** [comment]
@all-contributors add @superscratch444tre for translation

**Comment by Hans5958** [comment]
@all-contributors add @Ezlambry for code

**Comment by Hans5958** [comment]
TEST

@all-contributors 

add @Hans5958 for translation
add @Auto5958 for translation

**Comment by Hans5958** [comment]
@all-contributors add SheepTester for code

**Comment by Hans5958** [comment]
@all-contributors add ErrorGamer2000 for code

**Comment by Hans5958** [comment]
@all-contributors add ErrorGamer2000 for code

**Comment by GitHub027** [comment]
@all-contributors add @GitHub027 for bugs, ideas

**Comment by GitHub027** [comment]
> @GitHub027
> 
> @GitHub027 already contributed before to bug, ideas

well I don't see myself

**Comment by lisa-wolfgang** [comment]
@all-contributors add lisa-wolfgang for code

**Comment by lisa-wolfgang** [comment]
@all-contributors add @lisa-wolfgang for code

**Comment by Hans5958** [comment]
Adding few commiters that haven't been added

**Comment by Hans5958** [comment]
@allcontributors add @ZenithRogue for code

**Comment by Hans5958** [comment]
@allcontributors add @itta611 for code

**Comment by Hans5958** [comment]
@allcontributors add @Looky1173 for docs

**Comment by DNin01** [comment]
@allcontributors add @Hexagonl for video
