### ISSUE TITLE
Name change from wgyt735yt to wgyt

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/contributors#74]
On the website I appear twice :0 Once as @wgyt and once as @wgyt735yt, I think this might have to do with the .all-contributorsrc file containing wgyt735yt instead of wgyt. Could we also make the link to my site https?

_Originally posted by @wgyt in https://github.com/ScratchAddons/contributors/issues/71#issuecomment-760334216_

**Comment by wgyt** [comment]
I think this might have to do with [line 338 of the .all-contributorsrc file](https://github.com/ScratchAddons/contributors/blob/435812f71c379b926f951f1c3cf1cf797d7eea77/.all-contributorsrc#L338) because it says wgyt735yt not wgyt

**Comment by Hans5958** [comment]
+A for info, but really, I got this.
